### ISSUE TITLE
stdout 'data' events mishandled

### ISSUE THREAD

**Issue by networkimprov** [indutny/node.gzip#3]
child_process.stdout is a Stream, so you need to capture each of the buffers it posts and combine them on "exit"!

```
var output = [];
var outsize = 0;

gzip.stdout.on('data', function(data) {
    output.push(data);
    outsize += data.length;
});

gzip.on('exit', function(code) {
  var buf = new Buffer(outsize);
  for (var a=0, p=0; a < output.length; p += output[a++].length)
    output[a].copy(buf, p, 0);
  callback(code, buf);
}); 
```

**Comment by indutny** [comment]
Thank you, please update to 0.0.5.
Note that syntax has changed:
var gzip = require('gzip');

gzip('string', callback);

**Comment by networkimprov** [comment]
Sure thing. One of your users was quite confounded by that one :-)

http://groups.google.com/group/nodejs/browse_thread/thread/22b917e05c878bdb
